Mtelligent.Dashboard.Web/Controllers/GoalsController.cs
using Mtelligent.Dashboard.Data;
using Mtelligent.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Mtelligent.Dashboard.Web.Controllers
{
    [Authorize]
    public class GoalsController : Controller
    {
        private IGoalRepository goalRepository;

        public GoalsController(IGoalRepository goalRepository)
        {
            this.goalRepository = goalRepository;
        }

        public ActionResult Index()
        {
            var goals = goalRepository.GetAll();
            return View(goals);
        }

        public ActionResult Add()
        {
            var goal = new Goal();
            ViewBag.ActionName = "Add";
            ViewBag.Title = "Add a Goal";
            return View("EditGoal", goal);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(Goal goal)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    goal.CreatedBy = HttpContext.User.Identity.Name;
                    goal = goalRepository.Add(goal);
                    return Redirect("/Goals/");
                }
                else
                {
                    ViewBag.ErrorMessage = "There is a problem with one of your response.";
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "An Error Occurred while attempting to save that goal.";
            }

            
            ViewBag.ActionName = "Add";
            ViewBag.Title = "Add a Goal";
            return View("EditGoal", goal);
        }

        public ActionResult Update(int Id)
        {
            var goal = goalRepository.Get(Id);
            ViewBag.ActionName = "Update";
            ViewBag.Title = "Edit Goal";
            return View("EditGoal", goal);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Update(Goal goal)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    goal.UpdatedBy = HttpContext.User.Identity.Name;
                    goal = goalRepository.Update(goal);
                    return Redirect("/Goals/");
                }
                else
                {
                    ViewBag.ErrorMessage = "There is a problem with one of your response.";
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "An Error Occurred while attempting to save that goal.";
            }

            
            ViewBag.ActionName = "Update";
            ViewBag.Title = "Edit Goal";
            return View("EditGoal", goal);
        }

    }
}

Mtelligent.Dashboard.Web/Views/Goals/EditGoal.cshtml
@model Mtelligent.Entities.Goal

@{
    string action = ViewBag.ActionName;
    string errorMessage = ViewBag.ErrorMessage ?? "";
}
 <div class="content">
      <div class="row">

    <h1>@ViewBag.Title</h1>


@using (Html.BeginForm(action, "Goals", FormMethod.Post, new { @class="form-horizontal", role="form" } ))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.HiddenFor(m => m.Id)

    if (!string.IsNullOrEmpty(errorMessage))
    {
        <div class="alert alert-danger">@errorMessage</div>
    }
    
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.SystemName, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
                @Html.TextBoxFor(m => m.SystemName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.SystemName)
        </div>
    </div>
        <div class="form-group">
        @Html.LabelFor(m => m.Value, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Value, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Value)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.GACode, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
                @Html.TextBoxFor(m => m.GACode, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.GACode)
        </div>
    </div>
     <div class="form-group">
        @Html.LabelFor(m => m.CustomJS, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
                @Html.TextAreaFor(m => m.CustomJS, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.CustomJS)
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">@action</button>
        </div>
    </div>
}

@section Scripts{

    <script>
        $(document).ready(function () {
            $("#SystemName").focus(function () {
                if ($("#Name").val() != "" && $("#SystemName").val() == "") {
                    $("#SystemName").val($("#Name").val());
                }
            });

            if ($("#SystemName").val() != "") {
                $("#SystemName").attr("disabled", "disabled");
                $("#SystemName").after("<input type='hidden' name='" + $("#SystemName").attr("name") + "' value='" + $("#SystemName").val() + "'>");
            }
        });
    </script>

}

Mtelligent.Dashboard.Web/Views/Goals/Index.cshtml
@model IEnumerable<Mtelligent.Entities.Goal>

<div class="content">
  <div class="row">

    <h1>Goals</h1>
    <p>Goals are things you want your users to do. You use goals to determine how different variations of an experiment are performing against each other.</p>

    @if (Model.ToList().Count == 0)
    {
        <div class="alert alert-info">You currently have not configured any goals. Click "Add Goal" to add a goal.</div>
    }
    else
    {
        <table class="table table-striped">
            <tr>
                <th>Name</th>
                <th>System Name</th>
                <th>Value</th>
                <th>&nbsp;</th>
            </tr>

        @foreach (var goal in Model)
        {
            <tr>
                <td>@goal.Name</td>
                <td>@goal.SystemName</td>
                <td>@goal.Value</td>
                <td><a href="/Goals/Update?Id=@goal.Id" class="btn btn-primary btn-lg active" role="button">Edit</a></td>
            </tr>
            
        }
        </table>

    }

    <a href="/Goals/Add" class="btn btn-primary btn-lg active" role="button">Add Goal</a>
  </div>
</div>