Mtelligent.Dashboard.Web/ViewModels/CohortViewModel.cs
using Mtelligent.Configuration;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Mtelligent.Dashboard.Web.ViewModels
{
    public class CohortViewModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [Display(Name="System Name")]
        public string SystemName { get; set; }

        public List<CohortType> CohortTypes { get; set; }

        [Display(Name = "Cohort Type")]
        [Required]
        public string SelectedCohortType { get; set; }

        public int Id { get; set; }

        public List<CustomCohortPropertyInfo> Properties { get; set; }
    }

    public class CustomCohortPropertyInfo
    {
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public bool Required { get; set; }
        public string Value { get; set; }
    }
}

Mtelligent.Dashboard.Web/Controllers/CohortsController.cs
using Mtelligent.Configuration;
using Mtelligent.Dashboard.Data;
using Mtelligent.Dashboard.Web.ViewModels;
using Mtelligent.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Mtelligent.Dashboard.Web.Controllers
{
    [Authorize]
    public class CohortsController : Controller
    {
        private ICohortRepository cohortRepository;

        public CohortsController(ICohortRepository cohortRepository)
        {
            this.cohortRepository = cohortRepository;
        }

        // GET: /Cohorts/

        public ActionResult Index()
        {
            var cohorts = cohortRepository.GetAll();

            var config = (MtelligentSection)ConfigurationManager.GetSection("Mtelligent");
            ViewBag.Editable = config.Cohorts.ToList().Where(a => a.AllowNew).ToList();

            return View(cohorts);
        }

        public ActionResult Add()
        {
            CohortViewModel model = new CohortViewModel();
            var config = (MtelligentSection)ConfigurationManager.GetSection("Mtelligent");
            model.CohortTypes = config.Cohorts.ToList().Where(a => a.AllowNew).ToList();
            return View(model);
        }

        public ActionResult Update(int Id)
        {
            CohortViewModel model = new CohortViewModel();

            var cohort = cohortRepository.Get(Id);
            model.Name = cohort.Name;
            model.SystemName = cohort.SystemName;
            model.Id = Id;

            var config = (MtelligentSection)ConfigurationManager.GetSection("Mtelligent");
            model.CohortTypes = config.Cohorts.ToList().Where(a => a.AllowNew).ToList();

            var cohortType = config.Cohorts.ToList().Where(a => a.TypeName == cohort.TypeName).FirstOrDefault();
            model.SelectedCohortType = cohortType.Name;

            model.Properties = new List<CustomCohortPropertyInfo>();

            foreach (var propInfo in cohort.GetType().GetProperties())
            {
                if (Attribute.IsDefined(propInfo, typeof(UserEditableAttribute)))
                {
                    var name = propInfo.Name;

                    if (Attribute.IsDefined(propInfo, typeof(DisplayAttribute)))
                    {
                        var attr = (DisplayAttribute[])propInfo.GetCustomAttributes(typeof(DisplayAttribute), false);
                        if (attr.Length > 0)
                        {
                            name = attr[0].Name;
                        }
                    }

                    var required = Attribute.IsDefined(propInfo, typeof(RequiredAttribute));

                    var info = new CustomCohortPropertyInfo()
                    {
                        Name = propInfo.Name,
                        DisplayName = name,
                        Required = required,
                        Value = propInfo.GetValue(cohort).ToString()
                    };

                    model.Properties.Add(info);
                }
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(CohortViewModel viewModel)
        {
            var config = (MtelligentSection)ConfigurationManager.GetSection("Mtelligent");

            try
            {
                if (ModelState.IsValid)
                {
                   
                    var cohortType = config.Cohorts[viewModel.SelectedCohortType];                    

                    Type t = Type.GetType(cohortType.TypeName);
                    Cohort cohort = Activator.CreateInstance(t) as Cohort;
                    cohort.Name = viewModel.Name;
                    cohort.SystemName = viewModel.SystemName;
                    cohort.TypeName = cohortType.TypeName;

                    foreach (var propInfo in t.GetProperties())
                    {
                        if (Attribute.IsDefined(propInfo, typeof(UserEditableAttribute)))
                        {
                            if (Request["prop-" + propInfo.Name] != null)
                            {
                                if (propInfo.PropertyType == typeof(string))
                                {
                                    propInfo.SetValue(cohort, Request["prop-" + propInfo.Name]);
                                }

                                if (propInfo.PropertyType == typeof(DateTime))
                                {
                                    if (Request["prop-" + propInfo.Name] != string.Empty)
                                    {
                                        propInfo.SetValue(cohort, DateTime.Parse(Request["prop-" + propInfo.Name]));
                                    }
                                }
                            }
                        }
                    }

                    cohort.CreatedBy = HttpContext.User.Identity.Name;
                    cohort = cohortRepository.Add(cohort);

                    return Redirect("/Cohorts/");
                }
                else
                {
                    ViewBag.ErrorMessage = "There is a problem with one of your response.";
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "There is a problem saving the cohort.";
            }

            viewModel.CohortTypes = config.Cohorts.ToList().Where(a => a.AllowNew).ToList();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Update(CohortViewModel viewModel)
        {
            var config = (MtelligentSection)ConfigurationManager.GetSection("Mtelligent");

            try
            {
                if (ModelState.IsValid)
                {

                    var cohortType = config.Cohorts[viewModel.SelectedCohortType];

                    Type t = Type.GetType(cohortType.TypeName);
                    Cohort cohort = Activator.CreateInstance(t) as Cohort;
                    cohort.Name = viewModel.Name;
                    cohort.SystemName = viewModel.SystemName;
                    cohort.TypeName = cohortType.TypeName;
                    cohort.Id = viewModel.Id;

                    viewModel.Properties = new List<CustomCohortPropertyInfo>();

                    foreach (var propInfo in t.GetProperties())
                    {
                        if (Attribute.IsDefined(propInfo, typeof(UserEditableAttribute)))
                        {
                            if (Request["prop-" + propInfo.Name] != null)
                            {
                                if (propInfo.PropertyType == typeof(string))
                                {
                                    propInfo.SetValue(cohort, Request["prop-" + propInfo.Name]);
                                }

                                if (propInfo.PropertyType == typeof(DateTime))
                                {
                                    if (Request["prop-" + propInfo.Name] != string.Empty)
                                    {
                                        propInfo.SetValue(cohort, DateTime.Parse(Request["prop-" + propInfo.Name]));
                                    }
                                }
                               
                            }

                            var name = propInfo.Name;

                            if (Attribute.IsDefined(propInfo, typeof(DisplayAttribute)))
                            {
                                var attr = (DisplayAttribute[])propInfo.GetCustomAttributes(typeof(DisplayAttribute), false);
                                if (attr.Length > 0)
                                {
                                    name = attr[0].Name;
                                }
                            }

                            var required = Attribute.IsDefined(propInfo, typeof(RequiredAttribute));

                            viewModel.Properties.Add(new CustomCohortPropertyInfo()
                            {
                                Name = propInfo.Name,
                                DisplayName = name,
                                Required = required,
                                Value = Request["prop-" + propInfo.Name]
                            });
                        }
                    }

                    cohort.UpdatedBy = HttpContext.User.Identity.Name;
                    cohort = cohortRepository.Update(cohort);

                    return Redirect("/Cohorts/");
                }
                else
                {
                    ViewBag.ErrorMessage = "There is a problem with one of your response.";
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "There is a problem saving the cohort.";
            }

            viewModel.CohortTypes = config.Cohorts.ToList().Where(a => a.AllowNew).ToList();

            return View(viewModel);
        }

        public ActionResult Questions(string type)
        {
            var config = (MtelligentSection)ConfigurationManager.GetSection("Mtelligent");
            var cohortType = config.Cohorts[type];
            if (cohortType == null)
            {
                return Content("Invalid Cohort Type");
            }

            Type t = Type.GetType(cohortType.TypeName);

            List<CustomCohortPropertyInfo> properties = new List<CustomCohortPropertyInfo>();

            foreach (var propInfo in t.GetProperties())
            {
                if (Attribute.IsDefined(propInfo, typeof(UserEditableAttribute)))
                {
                    var name = propInfo.Name;

                    if (Attribute.IsDefined(propInfo, typeof(DisplayAttribute)))
                    {

Mtelligent.Dashboard.Web/Views/Cohorts/Add.cshtml
@model Mtelligent.Dashboard.Web.ViewModels.CohortViewModel

@{
    string errorMessage = ViewBag.ErrorMessage ?? "";
}


<div class="content">
  <div class="row">

    <h1>Add Cohort</h1>

      @using (Html.BeginForm("Add", "Cohorts", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
      {
           @Html.AntiForgeryToken()
           @Html.ValidationSummary(true)

        if (!string.IsNullOrEmpty(errorMessage))
        {
            <div class="alert alert-danger">@errorMessage</div>
        }
        
        <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name)
        </div>
        </div>
        <div class="form-group">
        @Html.LabelFor(m => m.SystemName, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
                @Html.TextBoxFor(m => m.SystemName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.SystemName)
        </div>
        </div>
        <div class="form-group">
        @Html.LabelFor(m => m.SelectedCohortType, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
                @Html.DropDownListFor(m => m.SelectedCohortType, new SelectList(Model.CohortTypes, "Name","Name"), "Select a Type", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.SelectedCohortType)
        </div>
        </div>
        
          <div id="AdditionalQuestions">

          </div>  
        
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Add Cohort</button>
            </div>
        </div>  
          
      }

  </div>
</div>

@section Scripts{

    <script>
        $(document).ready(function () {
            $("#SystemName").focus(function () {
                if ($("#Name").val() != "" && $("#SystemName").val() == "") {
                    $("#SystemName").val($("#Name").val());
                }
            });

            $("#SelectedCohortType").change(function () {
                if ($("#SelectedCohortType").val().length > 0) {
                    var ctype = $("#SelectedCohortType").val();
                    $.get("/Cohorts/Questions?type=" + ctype, function (data) {
                        console.log("got Data");
                        $("#AdditionalQuestions").html(data);
                        //To do: Enable validation of dynamically added fields.
                    });
                }
            });
        });
    </script>
}

Mtelligent.Dashboard.Web/Views/Cohorts/Index.cshtml
@model IEnumerable<Mtelligent.Entities.Cohort>

@{
    var counter=0;
    List<Mtelligent.Configuration.CohortType> editable = ViewBag.Editable as List<Mtelligent.Configuration.CohortType>;
}
<div class="content">
  <div class="row">

    <h1>Cohorts</h1>
    <p>Cohorts define segments of users for which you can target experiments or compare conversion rates.</p>

    @if (Model.ToList().Count == 0)
    {
        <div class="alert alert-info">You currently have not configured any cohorts. Click "Add Cohort" to add a cohort.</div>
    }
    else
    {
        <table class="table table-striped">
            <tr>
                <th>Name</th>
                <th>System Name</th>
                <th>Type</th>
                <th>&nbsp;</th>
            </tr>

        @foreach (var cohort in Model)
        {
            counter++;
            <tr>
                <td>@cohort.Name</td>
                <td>@cohort.SystemName</td>
                <td>@cohort.TypeName</td>
                <td>
                    @if (editable.FirstOrDefault(a=>a.TypeName == cohort.TypeName) != null)
                    {
                        <a href="/Cohorts/Update?Id=@cohort.Id" class="btn btn-primary btn-lg active" role="button">Edit</a>
                    }
                </td>
            </tr>
            
        }
        </table>

    }

    <a href="/Cohorts/Add" class="btn btn-primary btn-lg active" role="button">Add Cohort</a>
  </div>
</div>

Mtelligent.Dashboard.Web/Views/Cohorts/Questions.cshtml
@model IEnumerable<Mtelligent.Dashboard.Web.ViewModels.CustomCohortPropertyInfo>

@{
    ViewBag.Title = "Questions";
    Layout = "";
}

@foreach (var item in Model)
{

        <div class="form-group">
        <label class="col-sm-2 control-label" for="prop-@item.Name">@item.DisplayName</label>
        <div class="col-sm-10">
                <input class="form-control" data-val="@item.Required" data-val-required="The @item.DisplayName field is required." id="prop-@item.Name" name="prop-@item.Name" type="text" value="@item.Value">
                <span class="field-validation-valid" data-valmsg-for="prop-@item.Name" data-valmsg-replace="true"></span>
        </div>
        </div>
}

Mtelligent.Dashboard.Web/Views/Cohorts/Update.cshtml
@model Mtelligent.Dashboard.Web.ViewModels.CohortViewModel

@{
    string errorMessage = ViewBag.ErrorMessage ?? "";
}


<div class="content">
  <div class="row">

    <h1>Update Cohort</h1>

      @using (Html.BeginForm("Update", "Cohorts", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
      {
           @Html.AntiForgeryToken()
           @Html.ValidationSummary(true)

           @Html.HiddenFor(m => m.Id)
           @Html.HiddenFor(m => m.SelectedCohortType)

        if (!string.IsNullOrEmpty(errorMessage))
        {
            <div class="alert alert-danger">@errorMessage</div>
        }
        
        <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name)
        </div>
        </div>
        <div class="form-group">
        @Html.LabelFor(m => m.SystemName, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
                @Html.TextBoxFor(m => m.SystemName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.SystemName)
        </div>
        </div>
        <div class="form-group">
        @Html.LabelFor(m => m.SelectedCohortType, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
                @Html.DropDownListFor(m => m.SelectedCohortType, new SelectList(Model.CohortTypes, "Name","Name"), "Select a Type", new { @class = "form-control", disabled="disabled" })
                @Html.ValidationMessageFor(m => m.SelectedCohortType)
        </div>
        </div>
        
        @Html.Partial("Questions", Model.Properties)
        
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Update Cohort</button>
            </div>
        </div>  
          
      }

  </div>
</div>

@section Scripts{

    <script>
        $(document).ready(function () {

            if ($("#SystemName").val() != "") {
                $("#SystemName").attr("disabled", "disabled");
                $("#SystemName").after("<input type='hidden' name='" + $("#SystemName").attr("name") + "' value='" + $("#SystemName").val() + "'>");
            }
        });
    </script>
}