Mtelligent.Dashboard.Web/ViewModels/ExperimentViewModel.cs
using Mtelligent.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mtelligent.Dashboard.Web.ViewModels
{
    public class ExperimentViewModel
    {
        public Experiment Experiment { get; set; }
        public List<Cohort> Cohorts { get; set; }
        public List<Goal> Goals { get; set; }
    }
}

Mtelligent.Dashboard.Web/Controllers/ExperimentsController.cs
using Mtelligent.Dashboard.Data;
using Mtelligent.Dashboard.Web.ViewModels;
using Mtelligent.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mtelligent.Dashboard.Web.Controllers
{
    [Authorize]
    public class ExperimentsController : Controller
    {
        private IExperimentRepository experimentRepository;
        private ICohortRepository cohortRepository;
        private IGoalRepository goalRepository;

        public ExperimentsController(IExperimentRepository experimentRepository, ICohortRepository cohortRepository, IGoalRepository goalRepository)
        {
            this.experimentRepository = experimentRepository;
            this.cohortRepository = cohortRepository;
            this.goalRepository = goalRepository;
        }

        //
        // GET: /Experiments/
        public ActionResult Index()
        {
            var experiments = experimentRepository.GetAll();
            return View(experiments);
        }


        public ActionResult Add()
        {
            ExperimentViewModel viewModel = new ExperimentViewModel();
            viewModel.Experiment = null;
            viewModel.Cohorts = cohortRepository.GetAll().ToList();
            viewModel.Goals = goalRepository.GetAll().ToList();
            return View(viewModel);
        }

        public ActionResult Update(int Id)
        {
            ExperimentViewModel viewModel = new ExperimentViewModel();
            viewModel.Experiment = experimentRepository.Get(Id);
            viewModel.Cohorts = cohortRepository.GetAll().ToList();
            viewModel.Goals = goalRepository.GetAll().ToList();
            return View(viewModel);
        }

        public ActionResult AddSegment(int Id)
        {
            var viewModel = new SegmentViewModel();

            var experiment = experimentRepository.Get(Id);
            viewModel.ExperimentName = experiment.Name;
            viewModel.Variables = experiment.Variables;
            viewModel.ExperimentId = experiment.Id;

            return View(viewModel);
        }

        public ActionResult UpdateSegment(int experimentId, int segmentId)
        {
            var viewModel = new SegmentViewModel();

            var experiment = experimentRepository.Get(experimentId);
            var segment = experiment.Segments.FirstOrDefault(a => a.Id == segmentId);
            viewModel.Segment = segment;    

            viewModel.ExperimentName = experiment.Name;
            viewModel.Variables = experiment.Variables;
            viewModel.ExperimentId = experiment.Id;

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(ExperimentViewModel viewModel, int hidNumVariables)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    viewModel.Experiment.CreatedBy = HttpContext.User.Identity.Name;
                    viewModel.Experiment.Variables = new List<string>();

                    for (int i = 0; i < hidNumVariables; i++)
                    {
                        var variable = Request["variable-" + i];
                        if (!string.IsNullOrEmpty(variable))
                        {
                            viewModel.Experiment.Variables.Add(variable);
                        }
                    }

                    viewModel.Experiment = experimentRepository.Add(viewModel.Experiment);
                    return Redirect("/Experiments/");
                }
                else
                {
                    ViewBag.ErrorMessage = "There is a problem with one of your responses.";
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "An Error Occurred while attempting to save that experiment.";
            }

            viewModel.Cohorts = cohortRepository.GetAll().ToList();
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Update(ExperimentViewModel viewModel, int hidNumVariables)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    viewModel.Experiment.UpdatedBy = HttpContext.User.Identity.Name;
                    viewModel.Experiment.Variables = new List<string>();

                    for (int i = 0; i < hidNumVariables; i++)
                    {
                        var variable = Request["variable-" + i];
                        if (!string.IsNullOrEmpty(variable))
                        {
                            viewModel.Experiment.Variables.Add(variable);
                        }
                    }

                    viewModel.Experiment = experimentRepository.Update(viewModel.Experiment);
                    return Redirect("/Experiments/");
                }
                else
                {
                    ViewBag.ErrorMessage = "There is a problem with one of your responses.";
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "An Error Occurred while attempting to save that experiment.";
            }

            viewModel.Cohorts = cohortRepository.GetAll().ToList();
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AddSegment(SegmentViewModel viewModel)
        {
            var experiment = experimentRepository.Get(viewModel.ExperimentId);

            try
            {
                if (ModelState.IsValid)
                {                    

                    viewModel.Segment.CreatedBy = HttpContext.User.Identity.Name;
                    viewModel.Segment.Variables = new Dictionary<string, string>();
                    viewModel.Segment.ExperimentId = viewModel.ExperimentId;

                    foreach(var variable in experiment.Variables)
                    {
                        var varValue = Request["prop-" + variable];
                        if (!string.IsNullOrEmpty(varValue))
                        {
                            viewModel.Segment.Variables.Add(variable, varValue);
                        }
                    }

                    viewModel.Segment = experimentRepository.AddSegment(viewModel.Segment);
                    return Redirect("/Experiments/Update?Id=" + experiment.Id);
                }
                else
                {
                    ViewBag.ErrorMessage = "There is a problem with one of your responses.";
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "An Error Occurred while attempting to save that segment.";
            }

            
            viewModel.ExperimentName = experiment.Name;
            viewModel.Variables = experiment.Variables;
            viewModel.ExperimentId = experiment.Id;

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult UpdateSegment(SegmentViewModel viewModel)
        {
            var experiment = experimentRepository.Get(viewModel.ExperimentId);

            try
            {
                if (ModelState.IsValid)
                {

                    viewModel.Segment.UpdatedBy = HttpContext.User.Identity.Name;
                    viewModel.Segment.Variables = new Dictionary<string, string>();
                    viewModel.Segment.ExperimentId = viewModel.ExperimentId;

                    foreach (var variable in experiment.Variables)
                    {
                        var varValue = Request["prop-" + variable];
                        if (!string.IsNullOrEmpty(varValue))
                        {
                            viewModel.Segment.Variables.Add(variable, varValue);
                        }
                    }

                    viewModel.Segment = experimentRepository.UpdateSegment(viewModel.Segment);
                    return Redirect("/Experiments/Update?Id=" + experiment.Id);
                }
                else
                {
                    ViewBag.ErrorMessage = "There is a problem with one of your responses.";
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "An Error Occurred while attempting to save that segment.";
            }


            viewModel.ExperimentName = experiment.Name;
            viewModel.Variables = experiment.Variables;
            viewModel.ExperimentId = experiment.Id;

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult UpdateSegments(int experimentId)
        {
            var experiment = experimentRepository.Get(experimentId);
            
            foreach (var segment in experiment.Segments)
            {
                var reqIsDefault = Request[segment.Id + "-IsDefault"];
                var reqTargetPercentage = Request[segment.Id + "-TargetPercentage"];

                if (!string.IsNullOrEmpty(reqIsDefault))
                {
                    segment.IsDefault = bool.Parse(reqIsDefault);
                }
                if (!string.IsNullOrEmpty(reqTargetPercentage))
                {
                    segment.TargetPercentage = double.Parse(reqTargetPercentage);
                }

                experimentRepository.UpdateSegment(segment);
            }

            return Redirect("/Experiments/Update?ID=" + experimentId);
        }
    }
}

Mtelligent.Dashboard.Web/Views/Experiments/Add.cshtml
@model Mtelligent.Dashboard.Web.ViewModels.ExperimentViewModel

@{
    string errorMessage = ViewBag.ErrorMessage ?? "";
}

<div class="content">
  <div class="row">

    <h1>Add Experiment</h1>

      
      @using (Html.BeginForm("Add", "Experiments", FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "expForm" }))
      {
           @Html.AntiForgeryToken()
           @Html.ValidationSummary(true)

            if (!string.IsNullOrEmpty(errorMessage))
            {
                <div class="alert alert-danger">@errorMessage</div>
            }
        
            <div class="form-group">
            @Html.LabelFor(m => m.Experiment.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Experiment.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Experiment.Name)
            </div>
            </div>
           <div class="form-group">
            @Html.LabelFor(m => m.Experiment.SystemName, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Experiment.SystemName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Experiment.SystemName)
            </div>
            </div>
            <div class="form-group">
            @Html.LabelFor(m => m.Experiment.TargetCohortId, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                    @Html.DropDownListFor(m => m.Experiment.TargetCohortId, new SelectList(Model.Cohorts, "Id", "Name"), "Select a Cohort", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Experiment.TargetCohortId)
            </div>
            </div>
          
            <div class="form-group">
            @Html.LabelFor(m => m.Experiment.GoalIds, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                    @Html.ListBoxFor(m => m.Experiment.GoalIds, new SelectList(Model.Goals, "Id", "Name"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Experiment.GoalIds)
            </div>
            </div>
          
            <div data-bind="foreach: variables">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="variable-1" data-bind="text: $index() == 0 ? 'Variables' : ''"></label>
                    <div class="col-sm-10">
                        <span class="glyphicon glyphicon-plus" data-bind="click: viewModel.addVariable" title="Add Another" style="position:absolute; right:-5px; margin-top:7px; margin-left:10px; cursor:pointer"></span> <input class="form-control" data-val="false" data-bind="attr: { id: 'variable-' + $index(), name: 'variable-' + $index() }" type="text" value="">
                    </div>
                </div>
            </div>
          
            <input type="hidden" id="hidNumVariables" name="hidNumVariables" data-bind="value: variables().length" />
          
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <div><button type="submit" class="btn btn-default">Add Experiment</button></div>
                </div>
            </div>  
      }

       <hr />

      <h2>Hypotheses</h2>

      <p class="lead">Hypotheses are proposed variations of an experiment. The Default Hypothesis will be shown to users that are not in the target cohort.</p>
          
      <div class="alert alert-info">You must create the experiment before you can add any hypotheses. After you Add the Experiment, click "Edit" next to the experiment to configure hypotheses. </div>

@section Scripts {
      <script src="~/Scripts/knockout-3.0.0.js"></script>
      <script src="~/Scripts/Experiment.js" ></script>
      <script>
          $(document).ready(function () {
              $("#Experiment_SystemName").focus(function () {
                  if ($("#Experiment_Name").val() != "" && $("#Experiment_SystemName").val() == "") {
                      $("#Experiment_SystemName").val($("#Experiment_Name").val());
                  }
              });

              viewModel.addVariable();

              ko.applyBindings(viewModel);
          });

      </script>

}

Mtelligent.Dashboard.Web/Views/Experiments/AddSegment.cshtml
@model Mtelligent.Dashboard.Web.ViewModels.SegmentViewModel

@{
    string errorMessage = ViewBag.ErrorMessage ?? "";
}

<div class="content">
  <div class="row">

    <h1>Add Hypothesis to Experiment: [@Model.ExperimentName]</h1>

      <p class="lead">Enter details for your hypothesis. You will be able to set the target percentage and select a default hypothesis on the Edit Experiment page after you create the segment.</p>

      @using (Html.BeginForm("AddSegment", "Experiments", FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "expForm" }))
      {
           @Html.AntiForgeryToken()
           @Html.ValidationSummary(true)

           @Html.HiddenFor(m=>m.ExperimentId)

            if (!string.IsNullOrEmpty(errorMessage))
            {
                <div class="alert alert-danger">@errorMessage</div>
            }
        
            <div class="form-group">
            @Html.LabelFor(m => m.Segment.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Segment.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Segment.Name)
            </div>
            </div>
           <div class="form-group">
            @Html.LabelFor(m => m.Segment.SystemName, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Segment.SystemName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Segment.SystemName)
            </div>
            </div>
            
            <hr />
          
            <h3>Hypothesis Variables</h3>
          
            foreach (var variable in Model.Variables)
            {
                var varValue = Model.Segment != null && Model.Segment.Variables != null && Model.Segment.Variables.ContainsKey(variable) ? Model.Segment.Variables[variable] : string.Empty;
                <div class="form-group">
                <label class="col-sm-2 control-label" for="prop-@variable">@variable</label>
                <div class="col-sm-10">
                        <input class="form-control" data-val="true" data-val-required="The @variable field is required." id="prop-@variable" name="prop-@variable" type="text" value="@varValue">
                        <span class="field-validation-valid" data-valmsg-for="prop-@variable" data-valmsg-replace="true"></span>
                </div>
                </div>
            }
            <hr />
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <div><button type="submit" class="btn btn-default">Add Hypothesis</button></div>
                </div>
            </div>  
      }

@section Scripts{
          <script>
              $(document).ready(function () {
                  $("#Segment_SystemName").focus(function () {
                      if ($("#Segment_Name").val() != "" && $("#Segment_SystemName").val() == "") {
                          $("#Segment_SystemName").val($("#Segment_Name").val());
                      }
                  });
              });
          </script>
}

Mtelligent.Dashboard.Web/Views/Experiments/Index.cshtml
@model IEnumerable<Mtelligent.Entities.Experiment>

<div class="content">
  <div class="row">

    <h1>Experiments</h1>
    <p>Experiments allow you to try out a feature in your application and understand it's impact.</p>

    @if (Model.ToList().Count == 0)
    {
        <div class="alert alert-info">You currently have not configured any experiments. Click "Add Experiment" to add an experiment.</div>
    }
    else
    {
        <table class="table table-striped">
            <tr>
                <th>Name</th>
                <th>System Name</th>
                <th>Cohort</th>
                <th>Hypotheses</th>
                <th>&nbsp;</th>
            </tr>

        @foreach (var experiment in Model)
        {
            <tr>
                <td>@experiment.Name</td>
                <td>@experiment.SystemName</td>
                <td>@experiment.TargetCohortName</td>
                <td>@experiment.SegmentCount</td>
                <td><a href="/Experiments/Update?Id=@experiment.Id" class="btn btn-primary btn-lg active" role="button">Edit</a></td>
            </tr>
            
        }
        </table>

    }

    <a href="/Experiments/Add" class="btn btn-primary btn-lg active" role="button">Add Experiment</a>
  </div>
</div>

Mtelligent.Dashboard.Web/Views/Experiments/Update.cshtml
@model Mtelligent.Dashboard.Web.ViewModels.ExperimentViewModel

@{
    string errorMessage = ViewBag.ErrorMessage ?? "";
}

<div class="content">
  <div class="row">

    <h1>Edit Experiment</h1>

      
      @using (Html.BeginForm("Update", "Experiments", FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "expForm" }))
      {
           @Html.AntiForgeryToken()
           @Html.ValidationSummary(true)

           @Html.HiddenFor(m=>m.Experiment.Id)

            if (!string.IsNullOrEmpty(errorMessage))
            {
                <div class="alert alert-danger">@errorMessage</div>
            }
        
            <div class="form-group">
            @Html.LabelFor(m => m.Experiment.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Experiment.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Experiment.Name)
            </div>
            </div>
           <div class="form-group">
            @Html.LabelFor(m => m.Experiment.SystemName, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Experiment.SystemName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Experiment.SystemName)
            </div>
            </div>
            <div class="form-group">
            @Html.LabelFor(m => m.Experiment.TargetCohortId, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                    @Html.DropDownListFor(m => m.Experiment.TargetCohortId, new SelectList(Model.Cohorts, "Id", "Name"), "Select a Cohort", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Experiment.TargetCohortId)
            </div>
            </div>
            <div class="form-group">
            @Html.LabelFor(m => m.Experiment.GoalIds, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                    @Html.ListBoxFor(m => m.Experiment.GoalIds, new SelectList(Model.Goals, "Id", "Name"), new { @class = "form-control", size=5 })
                    @Html.ValidationMessageFor(m => m.Experiment.GoalIds)
            </div>
            </div>
            <div data-bind="foreach: variables">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="variable-1" data-bind="text: $index() == 0 ? 'Variables' : ''"></label>
                    <div class="col-sm-10">
                        <span class="glyphicon glyphicon-plus" data-bind="click: viewModel.addVariable" title="Add Another" style="position:absolute; right:-5px; margin-top:7px; margin-left:10px; cursor:pointer"></span> <input class="form-control" data-val="false" data-bind="    attr: { id: 'variable-' + $index(), name: 'variable-' + $index() }, value : $data, disable: $index() < viewModel.initalVariableCount()" type="text">
                    </div>
                </div>
            </div>
          
            <input type="hidden" id="hidNumVariables" name="hidNumVariables" data-bind="value: variables().length" />
          
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <div><button type="submit" class="btn btn-default">Update Experiment</button></div>
                </div>
            </div>  
      }


      <hr />

      <h2>Hypotheses</h2>

      <p class="lead">Hypotheses are proposed variations of an experiment. The Default Hypothesis will be shown to users that are not in the target cohort.</p>
           
      <div class="alert alert-danger hide" id="clientSideErrors"></div>

    @if (Model.Experiment.Segments.Count == 0)
    {
        <div class="alert alert-info">You currently have not configured any hypotheses. Click "Add Hypothesis" to add a hypothesis to this experiment. </div>
    }
    else
    {
        using (Html.BeginForm("UpdateSegments", "Experiments", FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "segForm" }))
        {
            <input type="hidden" name="experimentId" value="@Model.Experiment.Id" />
        
        <table class="table table-striped">
            <tr>
                <th>Name</th>
                <th>System Name</th>
                <th>Target Percentage <span class="glyphicon glyphicon-resize-vertical" style="cursor:pointer" title="Auto Distribute Among Non Default Options" id="btnDistribute"></span></th>
                <th>Is Default</th>
                <th>&nbsp;</th>
            </tr>

        @foreach (var segment in Model.Experiment.Segments)
        {
            <tr>
                <td>@segment.Name</td>
                <td>@segment.SystemName</td>
                <td><input class="form-control targetPercentage" name="@segment.Id-TargetPercentage" type="text" value="@segment.TargetPercentage" /></td>
                <td><input class="form-control isDefault" name="@segment.Id-IsDefault" type="checkbox" checked="@segment.IsDefault" value="true" /></td>
                <td><a href="/Experiments/UpdateSegment?experimentId=@Model.Experiment.Id&segmentId=@segment.Id" class="btn btn-primary btn-lg active" role="button">Edit Details</a></td>
            </tr>
            
        }
        </table>

        <div class="form-group">
            <div class="col-sm-10">
                <div><button type="submit" class="btn btn-default">Save Hypotheses Changes</button></div>
            </div>
        </div>  
        <hr />
        
        }
        
    }

    <a href="/Experiments/AddSegment?Id=@Model.Experiment.Id" class="btn btn-primary btn-lg active" role="button">Add Hypothesis</a>
@section Scripts {
      <script src="~/Scripts/knockout-3.0.0.js"></script>
      <script src="~/Scripts/Experiment.js" ></script>
      <script>
          var variables = @Html.Raw(Json.Encode(Model.Experiment.Variables));

          $(document).ready(function () {
              if ($("#Experiment_SystemName").val() != "") {
                  $("#Experiment_SystemName").attr("disabled", "disabled");
                  $("#Experiment_SystemName").after("<input type='hidden' name='" + $("#Experiment_SystemName").attr("name") + "' value='" + $("#Experiment_SystemName").val() + "'>");
              }

              $.each(variables, function(index, variable){
                  viewModel.variables.push(variable);
              });
              
              viewModel.initalVariableCount(viewModel.variables().length);

              ko.applyBindings(viewModel);

              $(".isDefault").change(function(){
                  if ($(this).prop('checked')){
                      $(".isDefault").prop('checked', false);
                      $(this).prop('checked', true);
                  }
              });

              $("#btnDistribute").click(function(){
                  var numItems = $(".isDefault").length
                  var defID;

                  if ($("input.isDefault:checkbox:checked").length > 0){
                      numItems = numItems-1;
                      defID = $("input.isDefault:checkbox:checked").attr("name").split("-")[0];
                  }
                  var distribution = Math.floor(100/numItems);

                  var lastItem;
                  
                  $(".targetPercentage").each(function(index, item){
                      if ($(item).attr("name").split("-")[0] != defID){
                          $(item).val(distribution);
                          lastItem = $(item);
                      }
                      else{
                          $(item).val("0");
                      }
                        
                  });

                  lastItem.val(distribution + (100 - (numItems * distribution)));

              });

              $("#segForm").submit(function(event){
                  console.log("trying to submit form");

                  $("#clientSideErrors").addClass("hide");
                  
                  var sum = 0;
                  $(".targetPercentage").each(function(index, item){
                      console.log("adding:"  +  $(item).val());
                      sum +=  parseFloat($(item).val());
                  });

                  console.log("sum:"  + sum);

                  if (sum != 100){
                      $("#clientSideErrors").text("The Sum of the Target Percentages must equal 100.");
                      $("#clientSideErrors").removeClass("hide");
                      event.preventDefault();
                  }

                  if ($("input.isDefault:checkbox:checked").length == 0 && $("#Experiment_TargetCohortId option:selected").text() != "All Users")
                  {
                      $("#clientSideErrors").text("Since this experiment does not target all users, one of the options must be the default options.");
                      $("#clientSideErrors").removeClass("hide");
                      event.preventDefault();
                  }
              });
          });

      </script>

}

Mtelligent.Dashboard.Web/Views/Experiments/UpdateSegment.cshtml
@model Mtelligent.Dashboard.Web.ViewModels.SegmentViewModel

@{
    string errorMessage = ViewBag.ErrorMessage ?? "";
}

<div class="content">
  <div class="row">

    <h1>Update Hypothesis for Experiment: [@Model.ExperimentName]</h1>

      <p class="lead">Edit details for your hypothesis. You will be able to set the target percentage and select a default segment on the Edit Experiment page after you create the hypothesis.</p>

      @using (Html.BeginForm("UpdateSegment", "Experiments", FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "expForm" }))
      {
           @Html.AntiForgeryToken()
           @Html.ValidationSummary(true)

           @Html.HiddenFor(m=>m.ExperimentId)
           @Html.HiddenFor(m=>m.Segment.Id)

            if (!string.IsNullOrEmpty(errorMessage))
            {
                <div class="alert alert-danger">@errorMessage</div>
            }
        
            <div class="form-group">
            @Html.LabelFor(m => m.Segment.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Segment.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Segment.Name)
            </div>
            </div>
           <div class="form-group">
            @Html.LabelFor(m => m.Segment.SystemName, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Segment.SystemName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Segment.SystemName)
            </div>
            </div>
            
            <hr />
          
            <h3>Hypothesis Variables</h3>
          
            foreach (var variable in Model.Variables)
            {
                var varValue = Model.Segment != null && Model.Segment.Variables != null && Model.Segment.Variables.ContainsKey(variable) ? Model.Segment.Variables[variable] : string.Empty;
                <div class="form-group">
                <label class="col-sm-2 control-label" for="prop-@variable">@variable</label>
                <div class="col-sm-10">
                        <input class="form-control" data-val="true" data-val-required="The @variable field is required." id="prop-@variable" name="prop-@variable" type="text" value="@varValue">
                        <span class="field-validation-valid" data-valmsg-for="prop-@variable" data-valmsg-replace="true"></span>
                </div>
                </div>
            }
            <hr />
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <div><button type="submit" class="btn btn-default">Update Hypothesis</button></div>
                </div>
            </div>  
      }

@section Scripts{
          <script>
              $(document).ready(function () {
                  if ($("#Segment_SystemName").val() != "") {
                      $("#Segment_SystemName").attr("disabled", "disabled");
                      $("#Segment_SystemName").after("<input type='hidden' name='" + $("#Segment_SystemName").attr("name") + "' value='" + $("#Segment_SystemName").val() + "'>");
                  }
              });
          </script>
}