Mtelligent.Dashboard.Web/Controllers/SitesController.cs
using Mtelligent.Dashboard.Data;
using Mtelligent.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Mtelligent.Dashboard.Web.Controllers
{
    [Authorize]
    public class SitesController : Controller
    {
        private ISiteRepository siteRepository;

        public SitesController(ISiteRepository siteRepository)
        {
            this.siteRepository = siteRepository;
        }

        //
        // GET: /Sites/

        public ActionResult Index()
        {
            var sites = siteRepository.GetAll();
            return View(sites);
        }


        public ActionResult Add()
        {
            var site = new Site();
            return View(site);
        }

        [HttpPost]
        public ActionResult Add(Site site)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    site.CreatedBy = HttpContext.User.Identity.Name;
                    site = siteRepository.Add(site);
                    return Redirect("/Sites/");
                }
                else
                {
                    ViewBag.ErrorMessage = "There is a problem with one of your response.";
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "An Error Occurred while attempting to save that site.";
            }

            return View(site);
        }


        public ActionResult Update(int Id)
        {
            var site = siteRepository.Get(Id);
            return View(site);
        }

        [HttpPost]
        public ActionResult Update(Site site)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    site.UpdatedBy = HttpContext.User.Identity.Name;
                    site = siteRepository.Update(site);
                    return Redirect("/Sites/");
                }
                else
                {
                    ViewBag.ErrorMessage = "There is a problem with one of your response.";
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "An Error Occurred while attempting to save that site.";
            }

            return View(site);
        }

        [HttpPost]
        public ActionResult AddUrl(SiteUrl item)
        {
            try
            {
                item.CreatedBy = HttpContext.User.Identity.Name;
                var returnUrl = siteRepository.AddSiteUrl(item);
                return Json(returnUrl);
            }
            catch (Exception ex)
            {
                return Json("failure");
            }
        }

        [HttpPost]
        public ActionResult DeleteUrl(SiteUrl item)
        {
            try
            {
                item.UpdatedBy = HttpContext.User.Identity.Name;
                siteRepository.DeleteSiteUrl(item);
                return Json("success");
            }
            catch (Exception ex)
            {
                return Json("failure");
            }
        }
    }


}

Mtelligent.Dashboard.Web/Views/Sites/Add.cshtml
@model Mtelligent.Entities.Site

@{
    string errorMessage = ViewBag.ErrorMessage ?? "";
}

<div class="content">
  <div class="row">

    <h1>Add Site</h1>

      @using (Html.BeginForm("Add", "Sites", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
      {
           @Html.AntiForgeryToken()
           @Html.ValidationSummary(true)

        if (!string.IsNullOrEmpty(errorMessage))
        {
            <div class="alert alert-danger">@errorMessage</div>
        }
        
        <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name)
        </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Add Site</button>
            </div>
        </div>  
          
      }

  </div>
</div>

Mtelligent.Dashboard.Web/Views/Sites/Index.cshtml
@model IEnumerable<Mtelligent.Entities.Site>

<div class="content">
  <div class="row">

    <h1>Sites</h1>
    <p>Sites allow you to group urls together for simpler reporting. They are optional but useful if you are running multiple sites.</p>

    @if (Model.ToList().Count == 0)
    {
        <div class="alert alert-info">You currently have not configured any sites. Click "Add Site" to add a site.</div>
    }
    else
    {
        <table class="table table-striped">
            <tr>
                <th>Name</th>
                <th>Number of Urls</th>
                <th>&nbsp;</th>
            </tr>

        @foreach (var site in Model)
        {
            <tr>
                <td>@site.Name</td>
                <td>@site.Urls.Count</td>
                <td><a href="/Sites/Update?Id=@site.Id" class="btn btn-primary btn-lg active" role="button">Edit</a></td>
            </tr>
            
        }
        
            </table>
        
    }

      <a href="/Sites/Add" class="btn btn-primary btn-lg active" role="button">Add Site</a>

  </div>
</div>

Mtelligent.Dashboard.Web/Views/Sites/Update.cshtml
@model Mtelligent.Entities.Site

@{
    string errorMessage = ViewBag.ErrorMessage ?? "";
}

<div class="content">
  <div class="row">

    <h1>Update Site</h1>

      @using (Html.BeginForm("Update", "Sites", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
      {
           @Html.AntiForgeryToken()
           @Html.ValidationSummary(true)

           @Html.HiddenFor(m => m.Id)

        if (!string.IsNullOrEmpty(errorMessage))
        {
            <div class="alert alert-danger">@errorMessage</div>
        }
        
        <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name)
        </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Update Site</button>
            </div>
        </div>  
      }

      <hr />
          
        @if (Model.Urls.Count == 0)
        {
            <div class="alert alert-info">You currently have not configured any urls with this site. Enter a url and Click "Add Url" to add a url.</div>
        }
        else
        {
        <h2>Site Urls</h2>
            
        <table class="table table-striped">
            <tr>
                <th>Url</th>
                <th>&nbsp;</th>
            </tr>

        @foreach (var url in Model.Urls)
        {
            <tr>
                <td>@url.Url</td>
                <td><a href="#" class="btn btn-primary btn-lg active btnDeleteUrl" role="button" data-id="@url.Id">Delete</a></td>
            </tr>
            
        }
        
            </table>
        
    }

      <form class="form-inline" role="form">
        <div class="form-group">
            <input type="text" class="form-control" id="txtNewUrl" placeholder="Enter Url" style="width:500px" />             
        </div>
        <a href="#" class="btn btn-primary btn-lg active" id="btnAddUrl" role="button">Add</a>
     </form>

  </div>
</div>

@section Scripts {

    <script>
        var lastData;

        $(document).ready(function () {
            $("#btnAddUrl").click(function () {
                var newUrl = encodeURI($("#txtNewUrl").val());
                
                var siteUrl = {
                    Url: newUrl,
                    SiteId: @Model.Id,
                    Id: 0
                };
                lastData = siteUrl;
                $.ajax({
                    type: "POST",
                    url: "/Sites/AddUrl",
                    data: siteUrl,
                    success: function(data){
                        if (data != "failure"){
                            document.location.href = document.location.href;
                        }
                        else
                        {
                            alert("Error encountered");
                        }
                    }
                });

                return false;
            });

            $(".btnDeleteUrl").click(function () {
                var deleteId = $(this).attr("data-id");
                console.log(deleteId);

                var newUrl = encodeURI($("#txtNewUrl").val());
                
                var siteUrl = {
                    Id : deleteId,
                    SiteId: @Model.Id
                    };

                $.ajax({
                    type: "POST",
                    url: "/Sites/DeleteUrl",
                    data: siteUrl,
                    success: function(data){
                        if (data != "failure"){
                            document.location.href = document.location.href;
                        }
                        else
                        {
                            alert("Error encountered");
                        }
                    }
                });

                return false;
            });
        });
    </script>
}